// Generated by gencpp from file sensor_cdf/Array.msg
// DO NOT EDIT!


#ifndef SENSOR_CDF_MESSAGE_ARRAY_H
#define SENSOR_CDF_MESSAGE_ARRAY_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace sensor_cdf
{
template <class ContainerAllocator>
struct Array_
{
  typedef Array_<ContainerAllocator> Type;

  Array_()
    : data()
    , rows(0)
    , cols(0)  {
    }
  Array_(const ContainerAllocator& _alloc)
    : data(_alloc)
    , rows(0)
    , cols(0)  {
  (void)_alloc;
    }



   typedef std::vector<float, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<float>> _data_type;
  _data_type data;

   typedef uint32_t _rows_type;
  _rows_type rows;

   typedef uint32_t _cols_type;
  _cols_type cols;





  typedef boost::shared_ptr< ::sensor_cdf::Array_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::sensor_cdf::Array_<ContainerAllocator> const> ConstPtr;

}; // struct Array_

typedef ::sensor_cdf::Array_<std::allocator<void> > Array;

typedef boost::shared_ptr< ::sensor_cdf::Array > ArrayPtr;
typedef boost::shared_ptr< ::sensor_cdf::Array const> ArrayConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::sensor_cdf::Array_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::sensor_cdf::Array_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::sensor_cdf::Array_<ContainerAllocator1> & lhs, const ::sensor_cdf::Array_<ContainerAllocator2> & rhs)
{
  return lhs.data == rhs.data &&
    lhs.rows == rhs.rows &&
    lhs.cols == rhs.cols;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::sensor_cdf::Array_<ContainerAllocator1> & lhs, const ::sensor_cdf::Array_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace sensor_cdf

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::sensor_cdf::Array_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::sensor_cdf::Array_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::sensor_cdf::Array_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::sensor_cdf::Array_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::sensor_cdf::Array_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::sensor_cdf::Array_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::sensor_cdf::Array_<ContainerAllocator> >
{
  static const char* value()
  {
    return "62b5b442ae701eb893fd7e389d955602";
  }

  static const char* value(const ::sensor_cdf::Array_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x62b5b442ae701eb8ULL;
  static const uint64_t static_value2 = 0x93fd7e389d955602ULL;
};

template<class ContainerAllocator>
struct DataType< ::sensor_cdf::Array_<ContainerAllocator> >
{
  static const char* value()
  {
    return "sensor_cdf/Array";
  }

  static const char* value(const ::sensor_cdf::Array_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::sensor_cdf::Array_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32[] data\n"
"uint32 rows\n"
"uint32 cols\n"
;
  }

  static const char* value(const ::sensor_cdf::Array_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::sensor_cdf::Array_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.data);
      stream.next(m.rows);
      stream.next(m.cols);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Array_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::sensor_cdf::Array_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::sensor_cdf::Array_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "data: ";
    if (v.data.empty() || true)
      s << "[";
    for (size_t i = 0; i < v.data.size(); ++i)
    {
      if (true && i > 0)
        s << ", ";
      else if (!true)
        s << std::endl << indent << "  -";
      Printer<float>::stream(s, true ? std::string() : indent + "    ", v.data[i]);
    }
    if (v.data.empty() || true)
      s << "]";
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "rows: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.rows);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "cols: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.cols);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SENSOR_CDF_MESSAGE_ARRAY_H
